name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  clang-format:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Lint
      uses: DoozyX/clang-format-lint-action@v0.18.2
      with:
        clangFormatVersion: 14
  build:
    needs: clang-format
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Release -B build
      - name: Build
        run: cmake --build build
      - name: Run
        run: ./build/algorithms
