name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  clang-format:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Lint
      uses: DoozyX/clang-format-lint-action@v0.18.2
      with:
        clangFormatVersion: 14
  build:
    needs: clang-format
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Conan
        run: pip install conan==2.20.1
      - name: Configure Conan
        run: conan profile detect
      - name: Install Conan packages
        run: conan install . --output-folder=build --build=missing --settings compiler=gcc --settings compiler.cppstd=20 --settings build_type=Release
      - name: Configure
        run: cmake --preset conan-release
      - name: Build
        run: cmake --build --preset conan-release
      - name: Test
        working-directory: build
        run: ctest --verbose --preset conan-release
